version: '3.9'

services:
  labelbox-webhooks:
    image: labelbox-webhooks
    container_name: labelbox-webhooks
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
